module.exports={
    homePage:(req,res)=>{
        res.render("home")
    },
    contactUs:(req,res)=>{
        res.render("contactUs")
    },
    books:(req,res)=>{
        res.render("books")
    },
    Dashboard:(req,res)=>{
        res.render("Dashboard")
    },
    Categories:(req,res)=>{
        res.render("Categories")
    },
    IssueBooks:(req,res)=>{
        res.render("IssueBooks")
    }
}