module.exports={
    homePage:(req,res)=>{
        res.render("home")
    },
    contactUs:(req,res)=>{
        res.render("contactUs")
    },
    books:(req,res)=>{
        res.render("books")
    },
    Dashboard:(req,res)=>{
        res.render("Dashboard")
    }
}